#Automação de Relatórios de Vendas e Envio de E-mails com Python

##1. Importação das bibliotecas

In [2]:
!pip install sqlalchemy
from sqlalchemy import create_engine
import pandas as pd
import smtplib
import email.message
import logging
import os
from datetime import datetime

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.47)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)

##2. Configuração do LOGGER

In [3]:
logging.basicConfig(
    filename='execucao_pipeline.log',
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s',
    encoding='utf-8'
)

##3. Banco de Dados e Carga

In [15]:
engine = create_engine('sqlite:///datahub_sales.db')

try:
    df_vendas = pd.read_excel("/content/Vendas.xlsx") # Ajustado o path
    df_vendas.to_sql('vendas', con=engine, if_exists='replace', index=False)
    logging.info("Dados migrados para o SQL com sucesso.")
except Exception as e:
    logging.error(f"Erro na migração inicial: {e}")

##4. Cálculo do faturamento por loja

In [16]:
query_faturamento = """
SELECT
  [ID Loja],
  SUM([Valor Final]) as Faturamento
FROM vendas
GROUP BY [ID Loja]
"""
tabela_faturamento = pd.read_sql(query_faturamento, con=engine)
display(tabela_faturamento)

                             ID Loja  Faturamento
0                Bourbon Shopping SP      1726110
1         Center Shopping Uberlândia      1668921
2                  Iguatemi Campinas      1762419
3                 Iguatemi Esplanada      1699681
4                     Norte Shopping      1711968
5       Novo Shopping Ribeirão Preto      1678225
6        Palladium Shopping Curitiba      1721120
7          Parque Dom Pedro Shopping      1631630
8          Passei das Águas Shopping      1649014
9                  Ribeirão Shopping      1707122
10                    Rio Mar Recife      1722766
11        Rio Mar Shopping Fortaleza      1698430
12                 Salvador Shopping      1646739
13                    Shopping Barra      1653103
14        Shopping Center Interlagos      1640486
15  Shopping Center Leste Aricanduva      1682870
16                 Shopping Eldorado      1648111
17               Shopping Ibirapuera      1635060
18       Shopping Iguatemi Fortaleza      1674824
19              Shopping Midway Mall      1590441
20                  Shopping Morumbi      1586444
21                   Shopping Recife      1624879
22                Shopping SP Market      1721763
23          Shopping União de Osasco      1663770
24               Shopping Vila Velha      1731167

Aqui calculamos o faturamento total de cada loja, permitindo identificar quais geram maior receita.

##5. Cálculo da quantidade de produtos vendidos por loja

In [17]:
query_quantidade = """
SELECT
  [ID Loja],
  SUM([Quantidade]) as Quantidade
FROM vendas
GROUP BY [ID Loja]
ORDER BY Quantidade DESC;
  """
tabela_quantidade = pd.read_sql(query_quantidade, con=engine)
display(tabela_quantidade)

                             ID Loja  Quantidade
0                Shopping Vila Velha        9224
1        Palladium Shopping Curitiba        9091
2                     Norte Shopping        9014
3   Shopping Center Leste Aricanduva        8938
4         Rio Mar Shopping Fortaleza        8937
5                  Iguatemi Campinas        8935
6                 Shopping SP Market        8927
7                     Rio Mar Recife        8863
8                Bourbon Shopping SP        8863
9                  Ribeirão Shopping        8825
10      Novo Shopping Ribeirão Preto        8751
11          Shopping União de Osasco        8730
12               Shopping Ibirapuera        8723
13                 Shopping Eldorado        8719
14                 Salvador Shopping        8698
15        Shopping Center Interlagos        8675
16                    Shopping Barra        8638
17       Shopping Iguatemi Fortaleza        8629
18        Center Shopping Uberlândia        8627
19         Passei das Águas Shopping        8618
20                   Shopping Recife        8581
21                Iguatemi Esplanada        8580
22                  Shopping Morumbi        8508
23         Parque Dom Pedro Shopping        8388
24              Shopping Midway Mall        8206

Essa métrica indica o volume de vendas de cada unidade.

##6. Cálculo do ticket e Tabela Insights

In [18]:
query_insights = """
SELECT
  [ID Loja],
  SUM([Valor Final]) AS Faturamento_Total,
  SUM(Quantidade) AS Quantidade_Total,
  ROUND(SUM([Valor Final]) / SUM(Quantidade), 2) AS Ticket_Medio,
  COUNT(DISTINCT "Código Venda") AS Total_Pedidos
FROM vendas
GROUP BY [ID Loja]
ORDER BY Ticket_Medio DESC;
"""
tabela_insights = pd.read_sql(query_insights, con=engine)
display(tabela_insights)

,ID Loja,Faturamento_Total,Quantidade_Total,Ticket_Medio,Total_Pedidos
0,Iguatemi Esplanada,1699681,8580,198.0,2137
1,Iguatemi Campinas,1762419,8935,197.0,2144
2,Shopping Iguatemi Fortaleza,1674824,8629,194.0,2164
3,Rio Mar Recife,1722766,8863,194.0,2180
4,Parque Dom Pedro Shopping,1631630,8388,194.0,2100
5,Bourbon Shopping SP,1726110,8863,194.0,2208
6,Shopping Midway Mall,1590441,8206,193.0,2051
7,Ribeirão Shopping,1707122,8825,193.0,2118
8,Center Shopping Uberlândia,1668921,8627,193.0,2147
9,Shopping SP Market,1721763,8927,192.0,2151
10,Shopping Barra,1653103,8638,191.0,2122
11,Passei das Águas Shopping,1649014,8618,191.0,2155
12,Novo Shopping Ribeirão Preto,1678225,8751,191.0,2137
13,Shopping União de Osasco,1663770,8730,190.0,2090
14,Rio Mar Shopping Fortaleza,1698430,8937,190.0,2192
15,Shopping Recife,1624879,8581,189.0,2069
16,Shopping Eldorado,1648111,8719,189.0,2136
17,Shopping Center Interlagos,1640486,8675,189.0,2122
18,Salvador Shopping,1646739,8698,189.0,2184
19,Palladium Shopping Curitiba,1721120,9091,189.0,2218
20,Norte Shopping,1711968,9014,189.0,2182
21,Shopping Center Leste Aricanduva,1682870,8938,188.0,2188
22,Shopping Vila Velha,1731167,9224,187.0,2237
23,Shopping Ibirapuera,1635060,8723,187.0,2187
24,Shopping Morumbi,1586444,8508,186.0,2072

O ticket médio mostra quanto, em média, cada cliente gasta por compra em cada loja.

##7. Criando VIEW no SQL

In [19]:
create_view_sql = """
CREATE VIEW IF NOT EXISTS vw_insights_vendas AS
SELECT
    "ID Loja",
    SUM("Valor Final") AS Faturamento_Total,
    SUM(Quantidade) AS Quantidade_Total,
    ROUND(SUM("Valor Final") / SUM(Quantidade), 2) AS Ticket_Medio,
    COUNT(DISTINCT "Código Venda") AS Total_Pedidos
FROM vendas
GROUP BY "ID Loja";
"""
with engine.begin() as conn:
    conn.exec_driver_sql(create_view_sql)

In [20]:
df_view = pd.read_sql("SELECT * FROM vw_insights_vendas", con=engine)
display(df_view.head())

,ID Loja,Faturamento_Total,Quantidade_Total,Ticket_Medio,Total_Pedidos
0,Bourbon Shopping SP,1726110,8863,194.0,2208
1,Center Shopping Uberlândia,1668921,8627,193.0,2147
2,Iguatemi Campinas,1762419,8935,197.0,2144
3,Iguatemi Esplanada,1699681,8580,198.0,2137
4,Norte Shopping,1711968,9014,189.0,2182

##8. Função de envio automático de e-mail

In [22]:
def enviar_email(resumo_loja, loja):
    try:
        os.environ['EMAIL_USER'] = 'shikamarupirocudo@gmail.com'
        os.environ['EMAIL_PASSWORD'] = 'ormo srxu xtmi rark'
        email_origem = os.getenv("EMAIL_USER")
        senha = os.getenv("EMAIL_PASSWORD")

        if not email_origem or not senha:
            raise ValueError("Credenciais de e-mail não encontradas nas variáveis de ambiente.")

        server = smtplib.SMTP('smtp.gmail.com:587')
        server.starttls()
        server.login(email_origem, senha)

        corpo_email = f"""
        <p>Prezados,</p>
        <p>Segue relatório de vendas da loja <strong>{loja}</strong>:</p>
        {resumo_loja.to_html()}
        <p>Qualquer dúvida estou à disposição.</p>
        """

        msg = email.message.Message()
        msg['Subject'] = f"Relatório de vendas - {loja}"
        msg['From'] = email_origem
        msg['To'] = email_origem
        msg.add_header('Content-Type', 'text/html')
        msg.set_payload(corpo_email)

        server.sendmail(msg['From'], [msg['To']], msg.as_string().encode('utf-8'))
        server.quit()

        logging.info(f'SUCESSO: Relatório enviado para a loja {loja}')
        print(f"E-mail enviado para {loja}")

    except Exception as e:
        logging.error(f'FALHA: Erro ao enviar e-mail para {loja}. Detalhes: {str(e)}')
        print(f'Erro no envio para {loja}. Verifique o log.')

A função encapsula toda a lógica de envio automático de relatórios por e-mail utilizando SMTP.

##9. Envio do relatório geral

In [23]:
enviar_email(tabela_insights, "Relatório Geral (Diretoria)")

E-mail enviado para Relatório Geral (Diretoria)

##10. Envio automático para cada loja

In [ ]:
lista_lojas = df_vendas['ID Loja'].unique()

for loja in lista_lojas:
    tabela_loja = df_vendas.loc[df_vendas['ID Loja'] == loja, ['ID Loja', 'Quantidade', 'Valor Final']]
    resumo_loja = tabela_loja.groupby('ID Loja').sum()
    resumo_loja['Ticket Médio'] = resumo_loja['Valor Final'] / resumo_loja['Quantidade']
    enviar_email(resumo_loja, loja)

E-mail enviado para Iguatemi Esplanada
E-mail enviado para Norte Shopping
E-mail enviado para Rio Mar Shopping Fortaleza
E-mail enviado para Shopping Barra
E-mail enviado para Shopping Ibirapuera
E-mail enviado para Iguatemi Campinas
E-mail enviado para Shopping Center Leste Aricanduva
E-mail enviado para Passei das Águas Shopping
E-mail enviado para Shopping Recife
E-mail enviado para Shopping Midway Mall
E-mail enviado para Bourbon Shopping SP
E-mail enviado para Shopping Center Interlagos
E-mail enviado para Parque Dom Pedro Shopping
E-mail enviado para Center Shopping Uberlândia
E-mail enviado para Shopping União de Osasco
E-mail enviado para Shopping Eldorado
E-mail enviado para Shopping Vila Velha
E-mail enviado para Novo Shopping Ribeirão Preto
E-mail enviado para Rio Mar Recife
E-mail enviado para Palladium Shopping Curitiba
E-mail enviado para Shopping SP Market
E-mail enviado para Ribeirão Shopping
E-mail enviado para Shopping Iguatemi Fortaleza
E-mail enviado para Shopping Morumbi
E-mail enviado para Salvador Shopping

Esse laço permite o envio automático de relatórios personalizados para cada loja, eliminando trabalho manual.

###Deploy em Nuvem
O script poderia ser agendado em uma GitHub Action ou AWS Lambda para rodar todo dia às 8h da manhã. Recrutadores de Cloud/Dados amam saber que você pensa em "agendamento".

In [21]:
from google.colab import files

# Isso vai forçar o download do banco de dados para o seu computador
files.download('datahub_sales.db')